sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.13.3

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

addons:
  apt:
    packages:
      - python-virtualenv

before_install:
  - umask 022
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/marian-craciunescu/symantecbeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/marian-craciunescu/symantecbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/marian-craciunescu/symantecbeat/
  - cd $HOME/gopath/src/github.com/marian-craciunescu/symantecbeat/

install:
  - true

script:
  - make
  - mage fmt update
  - make $TARGETS

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
