################### Symantecbeat Configuration Example #########################

############################# Symantecbeat ######################################

symantecbeat:
  # Defines how often an event is sent to the output
  period: 10s
  url: https://usea1.r3.securitycloud.symantec.com/r3_epmp_i
  customer_id: "cim"
  domain_id: "domain"
  client_id: "id"
  client_secret: "secret"

output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["192.168.1.6:9092"]
  topic: symantecbeat
